### ISSUE TITLE
Option to modify ┬ │ ┼ ┴ ├ ┤┘└┌ ┐ glyph heights

### ISSUE THREAD

**Issue by CallumHoward** [source-foundry/font-line#23]
Hello, this issue is a feature-request/request-for-advice that is most likely way out of scope and potentially not even possible to apply consistently across different fonts --I am not enough of an expert to know. Perhaps there is an alternate tool that may do what I want.

From the readme, "font-line does not modify the glyph set or hints applied to the font". However, I would like to increase the height of four glyphs: ┬ │ ┼ ┴ ├ ┤┘└┌ ┐ so that the vertical components reach the top and the bottom.

Use case:
I use the monospaced font Inconsolata in a terminal with Tmux (which allows you to have multiple windows inside your terminal by rendering ASCII borders). It looks like this with the font line spacing increased by 80% with this tool:
![Screen Shot 2019-11-09 at 9 37 37 am](https://user-images.githubusercontent.com/7144420/68515397-e5350180-02d4-11ea-8d38-aef767f35fb4.jpg)

Once the line spacing is increased, the vertical border characters no longer span the full glyph height and appear broken. I would like it to appear unbroken:
![Screen Shot 2019-11-09 at 9 51 30 am](https://user-images.githubusercontent.com/7144420/68515945-b4ee6280-02d6-11ea-935b-476f0e2071ad.jpg)

In the image above I have made a hack-ey attempt adjusting the heights in FontForge, but it requires some guesswork and eyeballing and it requires a lot of trial and error. Is there a programmatic way to achieve this, stretch the glyphs to either vertically span from top to bottom, or alternatively, vertically scale these glyphs to compensate for the percentage line space increase?

Font link: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.0.0/InconsolataLGC.zip
font-line command: `font-line percent 80 Inconsolata\ LGC\ Nerd\ Font\ Complete.ttf`

**Comment by chrissimpkins** [comment]
Hi Callum!

You are correct that this tool does not change glyph outlines.  Automation of glyph subset outlines will not be something that we would support here based on the goal of this tool but we can certainly look into how to adjust your outlines so that they stretch to match your new vertical metrics.  

Will you post a font-line report after your line spacing changes and point to the source file(s) that you are using to build your fonts?

**Comment by chrissimpkins** [comment]
And those previous comments come with a giant caveat that on screen use for Windows and Linux will be influenced by instruction sets / hints so sometimes this is a bit tricky to achieve perfection.  This is the nature of font use for UI purposes :)

**Comment by CallumHoward** [comment]
Thank you for your quick response!

Here is the report:
```
 
=== Inconsolata LGC Nerd Font Complete-linegap80.ttf ===
Version 1.3;Nerd Fonts 2.0.0 
SHA1: 89cef6f41cbe8bee6194bb35d164e3d73b77b4e5

--- Metrics ---
[head] Units per Em: 	1024
[head] yMax: 		1161
[head] yMin: 		-297
[OS/2] CapHeight: 	---- (OS/2 table does not contain sCapHeight record)
[OS/2] xHeight: 	---- (OS/2 table does not contain sxHeight record)
[OS/2] TypoAscender: 	840
[OS/2] TypoDescender: 	-184
[OS/2] WinAscent: 	1353
[OS/2] WinDescent: 	489
[hhea] Ascent: 		1353
[hhea] Descent: 	-489

[hhea] LineGap: 	0
[OS/2] TypoLineGap: 	0

--- Height Calculations by Table Values ---
[OS/2] TypoAscender to TypoDescender: 	1024
[OS/2] WinAscent to WinDescent: 	1842
[hhea] Ascent to Descent: 		1842

--- Delta Values ---
WinAscent to TypoAscender: 	513
Ascent to TypoAscender: 	513
WinDescent to TypoDescender: 	305
Descent to TypoDescender: 	305

--- Ratios ---
(Typo Asc + Desc + Linegap) / UPM: 	1
(winAsc + winDesc) / UPM: 		1.8
(hhea Asc + Desc) / UPM: 		1.8
```

The font I am adapting is `Inconsolata LGC Bold Italic Nerd Font Complete.ttf` which I obtained from the [NerdFont website](https://www.nerdfonts.com) here:
https://github.com/ryanoasis/nerd-fonts/releases/download/v2.0.0/InconsolataLGC.zip

I am not too sure where to find the source files of this particular version of the font, but it is based on the original Inconsolata which has a few different source formats available on the site here:
https://levien.com/type/myfonts/inconsolata.html
and on Google's font repository here:
https://github.com/googlefonts/Inconsolata

**Comment by chrissimpkins** [comment]
Open the font-line modified *.ttf file in your font editor and try extending all upper vertical strokes in that character set to a value above 1353 units, say 1360 units.  And extend all lower vertical strokes in that character set to a value below -489, say -495 units.

<img width="374" alt="154do-image" src="https://user-images.githubusercontent.com/4249591/68522054-209fe380-0275-11ea-8efa-7f1da3d35052.png">

It looks wildly out of proportion to the rest of the glyph set. This is intentional because you are trying to span the leading space between lines.  This *should* take you into the clipping range and across the leading so that the vertical strokes appear joined.  It looks like the fonts that you are dealing with are not hinted so we don't need to consider that.  Export a new *.ttf font from the editor and give it a try.  May need to clear your font cache depending upon your platform.

It is likely possible to automate this but with the small glyph set is simpler to just edit the outlines.

**Comment by CallumHoward** [comment]
That worked great, thanks!

**Comment by chrissimpkins** [comment]
Perfect! Enjoy!

**Comment by chrissimpkins** [comment]
@CallumHoward if you change metrics you should be able to use WinAscent/Descent & Ascent/Descent to define max dimensions of glyphs on line and LineGap / TypoLineGap to define leading (here = 0). Stretch the shapes that you want to make contact across lines of text to meet or exceed those combined values.  👍
